// Code generated by klaviyo-cli-gen from api/openapi/stable.json; DO NOT EDIT.

package api

// DefaultRevision is the Klaviyo API revision the CLI pins by default,
// matching the vendored OpenAPI spec the commands were generated from.
const DefaultRevision = "2026-07-15"
