// Code generated by klaviyo-cli-gen; DO NOT EDIT.

package api

// DefaultRevision is the Klaviyo API revision the CLI pins by default,
// matching the OpenAPI spec the commands were generated from.
const DefaultRevision = "2026-07-15"
