// Code generated by klaviyo-cli-gen from api/openapi/beta.json; DO NOT EDIT.
// Spec revision: 2026-07-15.pre
//
// Placeholder subset: trimmed to the one operation the tests exercise, to
// keep this PR's generated churn minimal. The full beta table lands with
// the next spec regeneration (regenerate.sh in klaviyo-cli-gen).

package cli

var betaResourceOps = []opSpec{
	{Group: "campaigns", Name: "get-campaigns", OpID: "get_campaigns_beta", Summary: "Get Campaigns", Method: "GET", Path: "/api/campaigns",
		Description: "🚧 This endpoint is in beta and will be released in GA in our 2026-10-15 revision.\n\nA beta revision header (2026-07-15.pre) is required to use our beta APIs.\n\nGet all campaigns, with optional filtering.\n\nRate limits:\nBurst: 10/s\nSteady: 150/m\n\nScopes:\ncampaigns:read", Query: []queryParamSpec{
			{"fields[campaign-audience]", "fields-campaign-audience", "comma-separated attribute names to include in the response"},
			{"fields[campaign-message]", "fields-campaign-message", "comma-separated attribute names to include in the response"},
			{"fields[campaign]", "fields-campaign", "comma-separated attribute names to include in the response"},
			{"filter", "filter", "Allowed field(s)/operator(s): 'id': 'any' (string) 'name': 'contains' (string) 'archived': 'equals' (boolean)..."},
			{"include", "include", "comma-separated related resources to include in the response"},
			{"page[cursor]", "page-cursor", "pagination cursor from a previous response's links.next"},
			{"page[size]", "page-size", "Default: 100. Min: 1. Max: 100."},
			{"sort", "sort", "field to sort by; prefix with - for descending (e.g. -created)"},
		}, Paginated: true, Beta: true},
}
